apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: users-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "host.docker.internal"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "usersdb"
        - name: POSTGRES_USER
          value: "usersusr"
        - name: POSTGRES_PASSWORD
          value: "Pa55w0rd"